config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks

  devise_for :users
  resources :users, only: %i(show)

  namespace :admin do
    resources :users
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :task_labelings, through: :labelings, source: :task

  validates :name, presence: true

end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings, source: :label


  enum status: { 未着手🦖:0, 着手中🐕💨:1, 完了✅:3 }
  enum priority: { あとでいいや🙈: 0, やりたい🙉: 1,  今すぐやらなきゃ🙊: 2 }

  validates :title, presence: true, length: { maximum: 140 }
  validates :content, presence: true, length: { maximum: 500 }
  validates :status, presence: true

  scope :search_with_title, -> (title) {
    where("title LIKE ?", "%#{ title }%")
  }

  scope :search_with_content, -> (content) {
    where("content LIKE ?", "%#{ content }%")
  }

  scope :search_with_status, -> (status) {
    where(status: status)
  }

  scope :search_with_label, -> (label_id) {
    task_ids = Labeling.where(label_id: label_id).pluck(:task_id)
    where(id: task_ids)
  }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, presence: true

  before_update :update_last_administrator
  before_destroy :destroy_last_administrator

  private

  def update_last_administrator
    errors.add(:base, "だって最後のadmin userですもの😲")
    throw(:abort) if (self.admin == false && User.where(admin: true).size == 1) && self == User.find_by(admin: true)
  end

  def destroy_last_administrator
    if self.admin == true && User.where(admin: true).count == 1
      throw(:abort)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user
    if current_user.admin?
      @users = User.includes(:tasks)
    else
      render 'tasks/index', notice: t("view.template.not_admin")
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user.id)
    else
      render new_admin_user_path
    end
  end

  def show
    @tasks = @user.tasks
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render 'admin/users/edit'
    end
  end

  def destroy
    if @user.destroy
      unless current_user
        redirect_to new_user_session_path
      else
        render admin_users_path
      end
    else
      redirect_to admin_users_path
      flash[:notice] = "the last administrator cannot be deleted."
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :basic_certifiaction

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :admin])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :admin])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  private

  def login_requirement
    redirect_to new_user_session_path, notice: t("view.template.login?") unless user_signed_in?
  end

  # def basic_certifiaction
  #   authenticate_or_request_with_http_basic do |name, password|
  #     name == ENV['BASIC_AUTH_NAME'] && password == ENV['BASIC_AUTH_PASSWORD'] if Rails.env == "production"
  #   end
  # end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :login_requirement
  before_action :authenticate_user!, only: %i(new edit update destroy)
  before_action :set_task, only: %i(show edit update destroy)
  before_action :set_labels, only: %i(index new edit create)
  before_action :correct_user?, only: %i(show edit destroy)

  def index
    @tasks = current_user.tasks.order(created_at: :desc)

    if params[:sort_expired]
      @tasks = current_user.tasks.order(expires_on: :asc)
    else
      @tasks = current_user.tasks.order(created_at: :desc)
    end

    if params[:task].present?
      @tasks = @tasks.search_with_title(params[:task][:title])
      @tasks = @tasks.search_with_content(params[:task][:content])
      if params[:task][:status].present?
        @tasks = @tasks.search_with_status(params[:task][:status])
      end
      if params[:task][:label_id].present?
        @tasks = @tasks.search_with_label(params[:task][:label_id])
      end
    end
    @tasks = @tasks.page(params[:page]).per(5)
  end

  def show; end

  def new
    if params[:back]
      @task = Task.new(task_params)
    else
      @task = Task.new
    end
  end

  def edit; end

  def create
    # binding.pry
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: "taskを作成しました✨ "
    else
      render "new"
    end
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task.id), notice: "taskを更新しました✅ "
    else
      render "edit"
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "taskを削除しました🗑 "
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_labels
      @labels = Label.all
    end

    def task_params
      params.require(:task).permit(
        :title,
        :content,
        :expires_on,
        :status,
        :priority,
        label_ids: []
      )
    end

    def correct_user?
      @task = Task.find_by(id:params[:id])
      if @task.user_id != current_user.id
        flash[:notice] = t("view.task.no_rights")
        redirect_to tasks_path
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    redirect_to tasks_path, notice: t("view.task.diff_user") unless @user == current_user
  end

  # def edit
  # end

  private
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/edit.html.erb
<h2><%= t("view.task.edit") %></h2>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, t("layout.views.error_indicate")) %></h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true, url: admin_user_path) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :admin %>
  <%= f.check_box :admin %>

  <%= f.submit %>
<% end %>

<%= link_to t("view.template.user_index"), admin_users_path %>

app/views/admin/users/index.html.erb
<h2>ADMIN</h2>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, t("layout.views.error_indicate")) %></h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% @users.each do |user| %>
  <div>ID:<%= user.id%></div>
  <div>NAME:<%= user.name %></div>
  <div>EMAIL:<%= user.email %></div>
  <div>ADMIN:<%= user.admin %></div>
  <div>TASK_AMOUNT:<%= user.tasks.count %>
  <%= link_to t("view.task.edit"), edit_admin_user_path(user), class: 'btn btn-sm btn-outline-primary' %>
  <%= link_to t("view.task.destroy"), admin_user_path(user), method: :delete, data: { confirm: 'F**k you sure??????' }, class: 'btn btn-sm btn-outline-danger' %>
<% end %>

<br />
<span>
  <%= link_to t("view.template.user_new"), new_admin_user_path %>
</span>

app/views/admin/users/new.html.erb
 <h2><%= t("view.template.user_new") %></h2>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, t("layout.views.error_indicate")) %></h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true, url: admin_users_path) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :admin %>
  <%= f.check_box :admin %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

<%= link_to t("view.template.user_index"), admin_users_path %>

app/views/admin/users/show.html.erb
<h2><%= t("view.template.user_show") %></h2>

<h1><%= @user.name %></h1>
<p>ID:<%= @user.id%></p>
<p>NAME:<%= @user.name %></p>
<p>EMAIL:<%= @user.email %></p>
<p>ADMIN:<%= @user.admin %></p>

<%= link_to t("view.template.user_index"), admin_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">TaskApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

    <header>
      <% if user_signed_in? %>
        <%= link_to t("view.task.mypage"), user_path(current_user.id), class: 'btn btn-success' %>
        <%= link_to t("view.template.logout"), destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to t("view.template.login"), new_user_session_path, class: 'btn btn-success' %>
        <%= link_to t("view.template.sign_up"), new_user_registration_path, class: 'btn btn-primary' %>
      <% end %>
    </header>

    <% if user_signed_in? %>
      <div><%= t("view.template.current_user") %><%= current_user.name %></div>
    <% end %>

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t("view.task.title") %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label t("view.task.content") %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label t("view.task.expiration") %>
    <%= form.date_select :expires_on %>
  </div>

  <div class="field">
    <%= form.label t("view.task.status") %>
    <%= form.select :status, Task.statuses.keys %>
  </div>

  <div class="field">
    <%= form.label t("view.task.priority") %>
    <%= form.select :priority, Task.priorities.keys %>
  </div>

  <% if action_name == :new %>
    <% labels.each do |label| %>
      <div class="field">
        <%= form.check_box :label_ids,
          { multiple: true,
          checked: label[:checked],
          disabled: label[:disabled],
          include_hidden: false },
          label[:id]
        %>
        <label style="background-color: aquamarine">
          <%= label.name %>
        </label>
      </div>
    <% end %>
  <% else %>
    <%= form.collection_check_boxes :label_ids, @labels, :id, :name %>
  <% end %>

  <div class="actions">
    <%= form.submit t("view.template.new_task") %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1><%= t("view.task.edit") %></h1>

<%= render 'form', task: @task %>

<%= link_to t("view.task.show"), @task %> |
<%= link_to t("view.task.back"), tasks_path %>

app/views/tasks/index.html.erb
<h1><%= t("view.task.index") %></h1>

<div>
  <%= form_with(model: Task.new, local: true, method: :get, url: tasks_path) do |form| %>
    <%= form.label :title, t("view.task.title") %>
    <%= form.text_field :title %>

    <%= form.label :content, t("view.task.content") %>
    <%= form.text_field :content %>

    <%= form.label :status, t("view.task.status") %>
    <%= form.select :status, Task.statuses.keys, include_blank: true %>

      <%= form.label :search_with_label, t("view.task.label") %>
      <%= form.select :label_id, @labels.map{ |label| [label.name, label.id] }, include_blank: true, selected: "" %>

    <%= form.submit t("view.task.search"), class: 'btn btn-sm btn-outline-success my-2 my-sm-0' %>
  <% end %>
</div>

<%= link_to t("view.task.high_priority"), tasks_path(sort_expired: "true"), class: 'btn btn-sm btn-outline-dark' %>

<table>
  <thead>
    <tr>
      <th><%= t("view.task.title") %></th>
      <th><%= t("view.task.content") %></th>
      <th><%= t("view.task.status") %></th>
      <th><%= t("view.task.user") %></th>
      <th><%= t("view.task.priority") %></th>
      <th><%= t("view.task.expiration") %></th>
      <th><%= t("view.task.time") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @tasks %>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.content %></td>
          <td><%= t("view.task.status") %><%= task.status %></td>
          <td><%= t("view.task.user_name") %><%= task.user.name %></td>
          <td><%= t("view.task.priority") %><%= task.priority %></td>
          <td><%= t("view.task.expiration") %><%= task.expires_on %></td>
          <td><%= t("view.task.time") %><%= task.created_at.strftime('%Y/%m/%d %H:%M')  %></td>
          <td><%= link_to t("view.task.show"), task, class: 'btn btn-sm btn-outline-success' %></td>
          <td><%= link_to t("view.task.edit"), edit_task_path(task), class: 'btn btn-sm btn-outline-primary' %></td>
          <td><%= link_to t("view.task.destroy"), task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("view.template.new_task"), new_task_path, class: 'btn btn-sm btn-outline-dark' %>
<% if @tasks %>
  <%= paginate @tasks %>
<% end %>

app/views/tasks/new.html.erb
<h1><%= t("view.template.new_task") %></h1>

<%= render 'form', task: @task %>

<%= link_to t("view.task.index"), tasks_path %>

app/views/tasks/show.html.erb
<p>
<strong><%= t("view.task.title") %></strong>
  <%= @task.title %>
</p>

<p>
<strong><%= t("view.task.content") %></strong>
  <%= @task.content %>
</p>

<p>
<strong><%= t("view.task.expiration") %></strong>
  <%= @task.expires_on %>
</p>

<p>
<strong><%= t("view.task.status") %></strong>
  <%= @task.status %>
</p>

<p>
<strong><%= t("view.task.priority") %></strong>
  <%= @task.priority %>
</p>

<p>
<strong><%= t("view.task.user") %></strong>
  <%= @task.user.name %>
</p>

<%= link_to t("view.task.edit"), edit_task_path(@task) %> |
<%= link_to t("view.task.back"), tasks_path %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= t("view.task.user_email") %>: <%= @user.email %></p>

<br>
<%= link_to t("view.template.new_task"), new_task_path %>
<%= link_to t("view.task.index"), tasks_path %>
<br>